spring.application.name=HospitalManagementSystem

spring.datasource.driver-class-name=org.postgresql.Driver
spring.datasource.url=jdbc:postgresql://localhost:5432/HMS
spring.datasource.username=postgres
spring.datasource.password=yash5553

spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true

#enable all end points of apringBoot actuator to acess from web
management.endpoints.web.exposure.include=*

management.endpoint.health.show-details=always




